
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect    
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootlamp?serverTimezone=Asia/Seoul  # url 설정
    username: bootlamp_user  # 계정 설정
    password: bootlamp_user  # 비번 설정
    
mail:
  address:
    admin: jmkim7707@gmail.com    